spring:
  application:
    name: Individuals API

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KC_SERVER}/realms/${KC_REALM}

  docker:
    compose:
      enabled: false

server:
  port: ${INDIVIDUALS_API_PORT}

keycloak:
  server: ${KC_SERVER}
  realm: ${KC_REALM}
  auth:
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
