spring:
  application:
    name: Individuals API
  docker:
    compose:
      enabled: false

server:
  port: ${INDIVIDUALS_API_PORT}

keycloak:
  server: ${KC_PORT}
  realm: ${KC_REALM}
  auth:
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
