INSERT INTO person.countries (name, alpha2, alpha3, status)
VALUES ('United States', 'US', 'USA', 'ACTIVE'),
       ('China', 'CN', 'CHN', 'ACTIVE'),
       ('Germany', 'DE', 'DEU', 'ACTIVE'),
       ('Japan', 'JP', 'JPN', 'ACTIVE'),
       ('India', 'IN', 'IND', 'ACTIVE'),
       ('United Kingdom', 'GB', 'GBR', 'ACTIVE'),
       ('France', 'FR', 'FRA', 'ACTIVE'),
       ('Italy', 'IT', 'ITA', 'ACTIVE'),
       ('Canada', 'CA', 'CAN', 'ACTIVE'),
       ('South Korea', 'KR', 'KOR', 'ACTIVE'),
       ('Russia', 'RU', 'RUS', 'ACTIVE'),
       ('Brazil', 'BR', 'BRA', 'ACTIVE'),
       ('Australia', 'AU', 'AUS', 'ACTIVE'),
       ('Mexico', 'MX', 'MEX', 'ACTIVE'),
       ('Spain', 'ES', 'ESP', 'ACTIVE'),
       ('Indonesia', 'ID', 'IDN', 'ACTIVE'),
       ('Netherlands', 'NL', 'NLD', 'ACTIVE'),
       ('Saudi Arabia', 'SA', 'SAU', 'ACTIVE'),
       ('Switzerland', 'CH', 'CHE', 'ACTIVE'),
       ('Turkey', 'TR', 'TUR', 'ACTIVE');